# Generated by Django 4.2.16 on 2024-11-06 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_category_slug_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resurvation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resurvations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
