# Generated by Django 4.2.16 on 2024-11-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_address_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuitem',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Delivered')], default=0),
        ),
    ]
